from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Enum as SqlEnum,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from db.enums import SuggestionSourceEnum, SuggestionStatus, TaskCategory, Urgency

from .base import Base, HasCreatorId, NumberedPrimaryId, OrgId


class Suggestion(Base, OrgId, NumberedPrimaryId, HasCreatorId):
    """
    A proposal generated by an automation or AI agent.

    Suggestions are lightweight -- they hold a proposed action with configurable
    options.  When the manager acts on a suggestion it may spawn a Task, send a
    message, or simply be dismissed.
    """
    __tablename__ = "suggestions"

    title           = Column(String(500), nullable=True)
    body            = Column(Text, nullable=True)
    category        = Column(SqlEnum(TaskCategory, name="task_category_enum"), nullable=True)
    urgency         = Column(SqlEnum(Urgency, name="urgency_enum"), nullable=True)
    source          = Column(SqlEnum(SuggestionSourceEnum, name="suggestion_source_enum"), nullable=True)
    automation_key  = Column(String(100), nullable=True)      # which automation created it

    status          = Column(SqlEnum(SuggestionStatus, name="suggestion_status_enum"), nullable=False, default=SuggestionStatus.PENDING)

    # Configurable action buttons: [{key, label, action, variant}]
    options         = Column(JSON, nullable=True)
    # Which option.action the user picked
    action_taken    = Column(String(50), nullable=True)
    acted_at        = Column(DateTime, nullable=True)

    # Context needed to execute the chosen action
    # e.g. {vendor_id, vendor_name, draft_message, notify_tenant}
    action_payload  = Column(JSON, nullable=True)

    # Suggestion type -- maps to autonomy category for approval routing
    suggestion_type = Column(SqlEnum(TaskCategory, name="task_category_enum"), nullable=False, default=TaskCategory.MAINTENANCE)
    # Agent's risk assessment (0=safe to auto-approve, 10=must have human review)
    risk_score      = Column(Integer, nullable=True)

    # Context FKs
    property_id     = Column(String(36), nullable=True)
    unit_id         = Column(String(36), nullable=True)
    document_id     = Column(String(36), nullable=True)

    # AI conversation for this suggestion's chat thread
    ai_conversation_id = Column(Integer, nullable=True)

    # Task created from this suggestion (NULL until accepted; cascade-deleted with task)
    task_id = Column(Integer, nullable=True)

    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(UTC))
    updated_at = Column(DateTime, nullable=False, default=lambda: datetime.now(UTC))

    # Relationships
    ai_conversation = relationship("Conversation", foreign_keys=[ai_conversation_id])
    property        = relationship("Property", foreign_keys=[property_id])
    unit            = relationship("Unit", foreign_keys=[unit_id])
    task            = relationship("Task", foreign_keys=[task_id])
    document        = relationship("Document", foreign_keys=[document_id])

    __table_args__ = (
        UniqueConstraint("org_id", "id", name="uq_suggestions_org"),
        Index("ix_suggestions_status", "status"),
        ForeignKeyConstraint(
            ["org_id", "creator_id"],
            ["users.org_id", "users.id"],
        ),
        ForeignKeyConstraint(
            ["org_id", "property_id"],
            ["properties.org_id", "properties.id"],
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["org_id", "unit_id"],
            ["units.org_id", "units.id"],
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["org_id", "document_id"],
            ["documents.org_id", "documents.id"],
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["org_id", "ai_conversation_id"],
            ["conversations.org_id", "conversations.id"],
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["org_id", "task_id"],
            ["tasks.org_id", "tasks.id"],
            ondelete="CASCADE",
        ),
    )
