import uuid
from datetime import UTC, datetime

from sqlalchemy import JSON, Column, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.orm import relationship

from .base import Base


class Suggestion(Base):
    """
    A proposal generated by an automation or AI agent.

    Suggestions are lightweight — they hold a proposed action with configurable
    options.  When the manager acts on a suggestion it may spawn a Task, send a
    message, or simply be dismissed.
    """
    __tablename__ = "suggestions"

    id              = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    account_id      = Column(String(36), nullable=False)

    title           = Column(String(500), nullable=True)
    body            = Column(Text, nullable=True)
    category        = Column(String(20), nullable=True)
    urgency         = Column(String(20), nullable=True)
    source          = Column(String(25), nullable=True)      # "automation", "agent"
    automation_key  = Column(String(100), nullable=True)      # which automation created it

    status          = Column(String(20), nullable=False, default="pending")
        # pending | accepted | dismissed | expired

    # Configurable action buttons: [{key, label, action, variant}]
    options         = Column(JSON, nullable=True)
    # Which option.action the user picked
    action_taken    = Column(String(50), nullable=True)
    acted_at        = Column(DateTime, nullable=True)

    # Context needed to execute the chosen action
    # e.g. {vendor_id, vendor_name, draft_message, notify_tenant}
    action_payload  = Column(JSON, nullable=True)

    # Context FKs
    property_id     = Column(String(36), ForeignKey("properties.id", ondelete="SET NULL"), nullable=True)
    unit_id         = Column(String(36), ForeignKey("units.id", ondelete="SET NULL"), nullable=True)

    # AI conversation for this suggestion's chat thread
    ai_conversation_id = Column(
        String(36), ForeignKey("conversations.id", ondelete="SET NULL"), nullable=True,
    )

    # Task created from this suggestion (NULL until accepted; cascade-deleted with task)
    task_id = Column(
        String(36), ForeignKey("tasks.id", ondelete="CASCADE"), nullable=True,
    )

    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(UTC))
    updated_at = Column(DateTime, nullable=False, default=lambda: datetime.now(UTC))

    # Relationships
    ai_conversation = relationship("Conversation", foreign_keys=[ai_conversation_id])
    property        = relationship("Property")
    unit            = relationship("Unit")
    task            = relationship("Task")

    __table_args__ = (
        Index("ix_suggestions_status", "status"),
        Index("ix_suggestions_account", "account_id"),
    )
