"""add message tables

Revision ID: 1c3d25793b3b
Revises: 4173d52aa89d
Create Date: 2025-11-26 08:02:23.870133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c3d25793b3b'
down_revision: Union[str, Sequence[str], None] = '4173d52aa89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_contacts_account_id'), 'external_contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_email'), 'external_contacts', ['email'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('lease_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['account_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index('ix_conversations_account_updated', 'conversations', ['account_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_lease_id'), 'conversations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_conversations_unit_id'), 'conversations', ['unit_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='participant_type'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('account_user_id', sa.UUID(), nullable=True),
    sa.Column('external_contact_id', sa.UUID(), nullable=True),
    sa.Column('delivery_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'participant_type', 'tenant_id', 'account_user_id', 'external_contact_id', name='uq_conversation_participant_unique_entity')
    )
    op.create_index(op.f('ix_conversation_participants_account_user_id'), 'conversation_participants', ['account_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_external_contact_id'), 'conversation_participants', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_tenant_id'), 'conversation_participants', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='message_sender_type'), nullable=False),
    sa.Column('sender_tenant_id', sa.UUID(), nullable=True),
    sa.Column('sender_account_user_id', sa.UUID(), nullable=True),
    sa.Column('sender_external_contact_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_user_id'], ['account_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_external_contact_id'], ['external_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sent', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_account_user_id'), 'messages', ['sender_account_user_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_external_contact_id'), 'messages', ['sender_external_contact_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_tenant_id'), 'messages', ['sender_tenant_id'], unique=False)
    op.create_table('message_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_participant_id', sa.UUID(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_participant_id'], ['conversation_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'conversation_participant_id', name='uq_message_receipt_unique')
    )
    op.create_index(op.f('ix_message_receipts_conversation_participant_id'), 'message_receipts', ['conversation_participant_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_message_id'), 'message_receipts', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receipts_message_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_conversation_participant_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index(op.f('ix_messages_sender_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_external_contact_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_account_user_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_sent', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_participants_tenant_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_external_contact_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_account_user_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversations_unit_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lease_id'), table_name='conversations')
    op.drop_index('ix_conversations_account_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_external_contacts_email'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_account_id'), table_name='external_contacts')
    op.drop_table('external_contacts')
    # ### end Alembic commands ###
