"""add accounts, properties, units schema

Revision ID: 3aa05be53e6b
Revises: 1f25beace861
Create Date: 2025-11-10 01:26:12.198284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa05be53e6b'
down_revision: Union[str, Sequence[str], None] = '1f25beace861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'label', name='uq_units_property_label')
    )
    op.drop_constraint(op.f('leases_house_id_fkey'), 'leases', type_='foreignkey')
    op.drop_table('tenant_houses')
    op.drop_table('houses')
    op.add_column('leases', sa.Column('account_id', sa.UUID(), nullable=False))
    op.add_column('leases', sa.Column('unit_id', sa.UUID(), nullable=False))
    op.add_column('leases', sa.Column('property_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'leases', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leases', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leases', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('leases', 'house_id')
    op.add_column('tenants', sa.Column('account_id', sa.UUID(), nullable=False))
    op.add_column('tenants', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('tenants', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('tenants', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'tenants', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tenants', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'last_name')
    op.drop_column('tenants', 'first_name')
    op.drop_column('tenants', 'account_id')
    op.add_column('leases', sa.Column('house_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.create_foreign_key(op.f('leases_house_id_fkey'), 'leases', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.drop_column('leases', 'property_id')
    op.drop_column('leases', 'unit_id')
    op.drop_column('leases', 'account_id')
    op.create_table('houses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='houses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tenant_houses',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('house_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('tenant_houses_house_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_houses_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'house_id', name=op.f('tenant_houses_pkey'))
    )
    op.drop_table('units')
    op.drop_table('properties')
    op.drop_table('accounts')
    # ### end Alembic commands ###
