"""baseline schema

Revision ID: 3e66152ff9a1
Revises: 
Create Date: 2026-04-08 04:27:44.534474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e66152ff9a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_account_id'), 'agent_memory', ['account_id'], unique=False)
    op.create_index('ix_agent_memory_agent_type', 'agent_memory', ['agent_id', 'memory_type'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trace_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_account_id'), 'agent_traces', ['account_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_id'), 'agent_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_timestamp'), 'agent_traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_type'), 'agent_traces', ['trace_type'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('automation_revisions',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_revisions_account_id'), 'automation_revisions', ['account_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('suggestion_states', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_meta', sa.JSON(), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_account_id'), 'documents', ['account_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256_checksum'), 'documents', ['sha256_checksum'], unique=False)
    op.create_table('external_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_contacts_account_id'), 'external_contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_email'), 'external_contacts', ['email'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_account_id'), 'properties', ['account_id'], unique=False)
    op.create_table('task_number_sequences',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_account_id'), 'tenants', ['account_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'label', name='uq_units_property_label')
    )
    op.create_index(op.f('ix_units_account_id'), 'units', ['account_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tags_document_id'), 'document_tags', ['document_id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_account_id'), 'leases', ['account_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('lease_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_type', sa.String(length=20), nullable=True),
    sa.Column('parent_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('ai_initiated', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversations_lease_id'), 'conversations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_conversations_unit_id'), 'conversations', ['unit_id'], unique=False)
    op.create_index('ix_conversations_updated', 'conversations', ['updated_at'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('participant_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='participant_type'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('external_contact_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_prefs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'participant_type', 'tenant_id', 'external_contact_id', name='uq_conversation_participant_unique_entity')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_external_contact_id'), 'conversation_participants', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_tenant_id'), 'conversation_participants', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='message_sender_type'), nullable=False),
    sa.Column('sender_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('sender_external_contact_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('draft_reply', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('related_task_ids', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_external_contact_id'], ['external_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sent', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_external_contact_id'), 'messages', ['sender_external_contact_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_tenant_id'), 'messages', ['sender_tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('task_status', sa.String(length=20), nullable=True),
    sa.Column('task_mode', sa.String(length=25), nullable=True),
    sa.Column('source', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('lease_id', sa.String(length=36), nullable=True),
    sa.Column('ai_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('parent_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('external_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ai_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'task_number', name='uq_task_number_per_account')
    )
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_number'), 'tasks', ['task_number'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_table('document_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'task_id', name='uq_document_task')
    )
    op.create_index(op.f('ix_document_tasks_document_id'), 'document_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tasks_task_id'), 'document_tasks', ['task_id'], unique=False)
    op.create_table('message_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_participant_id', sa.String(length=36), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_participant_id'], ['conversation_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'conversation_participant_id', name='uq_message_receipt_unique')
    )
    op.create_index(op.f('ix_message_receipts_conversation_participant_id'), 'message_receipts', ['conversation_participant_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_message_id'), 'message_receipts', ['message_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=25), nullable=True),
    sa.Column('automation_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('ai_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ai_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_account_id'), 'suggestions', ['account_id'], unique=False)
    op.create_index('ix_suggestions_status', 'suggestions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suggestions_status', table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_account_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_message_receipts_message_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_conversation_participant_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index(op.f('ix_document_tasks_task_id'), table_name='document_tasks')
    op.drop_index(op.f('ix_document_tasks_document_id'), table_name='document_tasks')
    op.drop_table('document_tasks')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_messages_sender_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_external_contact_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_sent', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_participants_tenant_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_external_contact_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_conversations_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_unit_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lease_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_leases_account_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_document_tags_document_id'), table_name='document_tags')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_units_account_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_tenants_account_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('task_number_sequences')
    op.drop_index(op.f('ix_properties_account_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_external_contacts_email'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_account_id'), table_name='external_contacts')
    op.drop_table('external_contacts')
    op.drop_index(op.f('ix_documents_sha256_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_account_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_automation_revisions_account_id'), table_name='automation_revisions')
    op.drop_table('automation_revisions')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_agent_traces_trace_type'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_timestamp'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_account_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index('ix_agent_memory_agent_type', table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_account_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
