"""add account user

Revision ID: 4173d52aa89d
Revises: 73ddad9ad84c
Create Date: 2025-11-10 01:44:04.035529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4173d52aa89d'
down_revision: Union[str, Sequence[str], None] = '73ddad9ad84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_users_user_id'), 'account_users', ['user_id'], unique=False)
    op.drop_index(op.f('ix_accounts_admin_id'), table_name='accounts')
    op.drop_column('accounts', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_accounts_admin_id'), 'accounts', ['admin_id'], unique=False)
    op.drop_index(op.f('ix_account_users_user_id'), table_name='account_users')
    op.drop_table('account_users')
    # ### end Alembic commands ###
