"""add phone to account users

Revision ID: 42baa09c41ac
Revises: 1c3d25793b3b
Create Date: 2025-12-01 04:42:47.161700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42baa09c41ac'
down_revision: Union[str, Sequence[str], None] = '1c3d25793b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_users', 'phone')
    # ### end Alembic commands ###
