"""account references users table

Revision ID: 73ddad9ad84c
Revises: 3aa05be53e6b
Create Date: 2025-11-10 01:37:50.038235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ddad9ad84c'
down_revision: Union[str, Sequence[str], None] = '3aa05be53e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('admin_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_accounts_admin_id'), 'accounts', ['admin_id'], unique=False)
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accounts_admin_id'), table_name='accounts')
    op.drop_column('accounts', 'admin_id')
    # ### end Alembic commands ###
