"""Add entity_notes table for per-account context

Revision ID: 77b0816e014c
Revises: f0b363bb12b8
Create Date: 2026-04-09 01:59:14.727513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b0816e014c'
down_revision: Union[str, Sequence[str], None] = 'f0b363bb12b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'entity_type', 'entity_id', name='uq_entity_note_account')
    )
    op.create_index(op.f('ix_entity_notes_account_id'), 'entity_notes', ['account_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_entity_id'), 'entity_notes', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_notes_entity_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_account_id'), table_name='entity_notes')
    op.drop_table('entity_notes')
    # ### end Alembic commands ###
