"""baseline schema

Revision ID: 857fe4c65246
Revises: 
Create Date: 2026-04-11 06:45:50.582543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857fe4c65246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_index(op.f('ix_app_settings_org_id'), 'app_settings', ['org_id'], unique=False)
    op.create_table('task_number_sequences',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_users_org')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_agent_memory_org')
    )
    op.create_index('ix_agent_memory_agent_type', 'agent_memory', ['creator_id', 'memory_type'], unique=False)
    op.create_index(op.f('ix_agent_memory_org_id'), 'agent_memory', ['org_id'], unique=False)
    op.create_table('memory_items',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'creator_id', 'source_type', 'source_id', name='uq_memory_item_source'),
    sa.UniqueConstraint('org_id', 'id', name='uq_memory_items_org')
    )
    op.create_index('ix_memory_items_lookup', 'memory_items', ['org_id', 'creator_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_memory_items_org_id'), 'memory_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_memory_items_updated_at'), 'memory_items', ['updated_at'], unique=False)
    op.create_index('ix_memory_items_visibility', 'memory_items', ['org_id', 'creator_id', 'visibility'], unique=False)
    op.create_table('agent_traces',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trace_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_agent_traces_org')
    )
    op.create_index(op.f('ix_agent_traces_org_id'), 'agent_traces', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_id'), 'agent_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_timestamp'), 'agent_traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_type'), 'agent_traces', ['trace_type'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_meta', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_documents_server')
    )
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256_checksum'), 'documents', ['sha256_checksum'], unique=False)
    op.create_table('entity_notes',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'entity_type', 'entity_id', name='uq_entity_note_creator'),
    sa.UniqueConstraint('org_id', 'id', name='uq_entity_notes_org')
    )
    op.create_index(op.f('ix_entity_notes_entity_id'), 'entity_notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_org_id'), 'entity_notes', ['org_id'], unique=False)
    op.create_table('external_contacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_external_contacts_server')
    )
    op.create_index(op.f('ix_external_contacts_email'), 'external_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_external_contacts_org_id'), 'external_contacts', ['org_id'], unique=False)
    op.create_table('properties',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_properties_server')
    )
    op.create_index(op.f('ix_properties_org_id'), 'properties', ['org_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('schedule_display', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('repeat', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_output', sa.Text(), nullable=True),
    sa.Column('simulated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_scheduled_tasks_org')
    )
    op.create_index(op.f('ix_scheduled_tasks_org_id'), 'scheduled_tasks', ['org_id'], unique=False)
    op.create_table('tenants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'user_id'], ['users.org_id', 'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_tenants_server')
    )
    op.create_index(op.f('ix_tenants_org_id'), 'tenants', ['org_id'], unique=False)
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'tenant_id'], ['tenants.org_id', 'tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_units_server'),
    sa.UniqueConstraint('property_id', 'label', name='uq_units_property_label')
    )
    op.create_index(op.f('ix_units_org_id'), 'units', ['org_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'document_id'], ['documents.org_id', 'documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'tenant_id'], ['tenants.org_id', 'tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'unit_id'], ['units.org_id', 'units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_document_tags_server')
    )
    op.create_index(op.f('ix_document_tags_document_id'), 'document_tags', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tags_org_id'), 'document_tags', ['org_id'], unique=False)
    op.create_table('leases',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'tenant_id'], ['tenants.org_id', 'tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'unit_id'], ['units.org_id', 'units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_leases_server')
    )
    op.create_index(op.f('ix_leases_org_id'), 'leases', ['org_id'], unique=False)
    op.create_table('conversations',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('lease_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_type', sa.String(length=20), nullable=True),
    sa.Column('parent_conversation_id', sa.Integer(), nullable=True),
    sa.Column('ai_initiated', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'lease_id'], ['leases.org_id', 'leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'unit_id'], ['units.org_id', 'units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_conversations_server')
    )
    op.create_index(op.f('ix_conversations_lease_id'), 'conversations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_conversations_org_id'), 'conversations', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_conversations_unit_id'), 'conversations', ['unit_id'], unique=False)
    op.create_index('ix_conversations_updated', 'conversations', ['updated_at'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='participant_type'), nullable=False),
    sa.Column('delivery_prefs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'user_id'], ['users.org_id', 'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_conversation_participants_server')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_org_id'), 'conversation_participants', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('task_status', sa.Enum('SUGGESTED', 'ACTIVE', 'PAUSED', 'RESOLVED', 'DISMISSED', name='task_status_enum'), nullable=True),
    sa.Column('task_mode', sa.Enum('MANUAL', 'WAITING_APPROVAL', 'AUTONOMOUS', name='task_mode_enum'), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AI_SUGGESTION', 'AUTOMATION', 'AGENT', 'DOCUMENT', 'TENANT_REPORT', 'DEV_SIM', name='task_source_enum'), nullable=True),
    sa.Column('category', sa.Enum('RENT', 'MAINTENANCE', 'LEASING', 'COMPLIANCE', 'OTHER', name='task_category_enum'), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_enum'), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', name='task_priority_enum'), nullable=True),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('channel_type', sa.Enum('SMS', 'EMAIL', name='channel_type_enum'), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('lease_id', sa.String(length=36), nullable=True),
    sa.Column('ai_conversation_id', sa.Integer(), nullable=True),
    sa.Column('parent_conversation_id', sa.Integer(), nullable=True),
    sa.Column('external_conversation_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'ai_conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'external_conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'lease_id'], ['leases.org_id', 'leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'parent_conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'unit_id'], ['units.org_id', 'units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_tasks_server')
    )
    op.create_index(op.f('ix_tasks_org_id'), 'tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('TENANT', 'ACCOUNT_USER', 'EXTERNAL_CONTACT', name='message_sender_type'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('message_type', sa.Enum('MESSAGE', 'INTERNAL', 'APPROVAL', 'SUGGESTION', 'CONTEXT', 'THREAD', 'DRAFT_AI_REPLY', 'ACTION', name='message_type_enum'), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('draft_approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EDITED', name='draft_approval_status_enum'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'sender_id'], ['conversation_participants.org_id', 'conversation_participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_messages_id'),
    sa.UniqueConstraint('org_id', 'conversation_id', 'id', name='uq_messages_server')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sent', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('RENT', 'MAINTENANCE', 'LEASING', 'COMPLIANCE', 'OTHER', name='task_category_enum'), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_enum'), nullable=True),
    sa.Column('source', sa.Enum('AUTOMATION', 'AGENT', name='suggestion_source_enum'), nullable=True),
    sa.Column('automation_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DISMISSED', 'EXPIRED', name='suggestion_status_enum'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('suggestion_type', sa.Enum('RENT', 'MAINTENANCE', 'LEASING', 'COMPLIANCE', 'OTHER', name='task_category_enum'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('ai_conversation_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'ai_conversation_id'], ['conversations.org_id', 'conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'creator_id'], ['users.org_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'document_id'], ['documents.org_id', 'documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'property_id'], ['properties.org_id', 'properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id', 'task_id'], ['tasks.org_id', 'tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'unit_id'], ['units.org_id', 'units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id', name='uq_suggestions_org')
    )
    op.create_index(op.f('ix_suggestions_org_id'), 'suggestions', ['org_id'], unique=False)
    op.create_index('ix_suggestions_status', 'suggestions', ['status'], unique=False)
    op.create_table('message_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_participant_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'conversation_id', 'message_id'], ['messages.org_id', 'messages.conversation_id', 'messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id', 'conversation_participant_id'], ['conversation_participants.org_id', 'conversation_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'conversation_participant_id', name='uq_message_receipt_unique')
    )
    op.create_index(op.f('ix_message_receipts_conversation_participant_id'), 'message_receipts', ['conversation_participant_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_message_id'), 'message_receipts', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_org_id'), 'message_receipts', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receipts_org_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_message_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_conversation_participant_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index('ix_suggestions_status', table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_org_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_sent', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_org_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_org_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_conversations_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_unit_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_org_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lease_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_leases_org_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_document_tags_org_id'), table_name='document_tags')
    op.drop_index(op.f('ix_document_tags_document_id'), table_name='document_tags')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_units_org_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_org_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_scheduled_tasks_org_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_properties_org_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_external_contacts_org_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_email'), table_name='external_contacts')
    op.drop_table('external_contacts')
    op.drop_index(op.f('ix_entity_notes_org_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_entity_id'), table_name='entity_notes')
    op.drop_table('entity_notes')
    op.drop_index(op.f('ix_documents_sha256_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_agent_traces_trace_type'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_timestamp'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_org_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_agent_memory_org_id'), table_name='agent_memory')
    op.drop_index('ix_memory_items_visibility', table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_updated_at'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_org_id'), table_name='memory_items')
    op.drop_index('ix_memory_items_lookup', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_agent_memory_agent_type', table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('task_number_sequences')
    op.drop_index(op.f('ix_app_settings_org_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
