/**
 * E2E test: automation simulation -> task creation with vendor ->
 * vendor conversation visible in Chats -> open conversation -> messages load.
 *
 * Runs against the FULL backend (no mocking).
 * Start with: npx playwright test --config playwright-e2e.config.ts
 */

import { test, expect, Page } from '@playwright/test';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Log in via the backend and inject the JWT into localStorage. */
async function login(page: Page) {
  // Hit the login mutation directly to get a real JWT
  const res = await page.request.post('/graphql', {
    data: {
      query: `mutation { login(input: { password: "rentmate" }) { token } }`,
    },
  });
  const body = await res.json();
  const token = body.data?.login?.token;
  if (!token) throw new Error(`Login failed: ${JSON.stringify(body)}`);

  // Inject into localStorage before the page loads
  await page.addInitScript((t: string) => {
    localStorage.setItem('jwtToken', t);
  }, token);
}

/** Make an authenticated GraphQL request via the page's request context. */
async function gql(page: Page, query: string, variables: Record<string, unknown> = {}) {
  // Read token from a prior login call stored in test state
  const tokenRes = await page.request.post('/graphql', {
    data: {
      query: `mutation { login(input: { password: "rentmate" }) { token } }`,
    },
  });
  const token = (await tokenRes.json()).data?.login?.token;

  const res = await page.request.post('/graphql', {
    headers: { Authorization: `Bearer ${token}` },
    data: { query, variables },
  });
  const body = await res.json();
  if (body.errors?.length) throw new Error(`GraphQL error: ${JSON.stringify(body.errors)}`);
  return body.data;
}

/** Make an authenticated REST request. */
async function apiPost(page: Page, path: string, body: Record<string, unknown>) {
  const tokenRes = await page.request.post('/graphql', {
    data: {
      query: `mutation { login(input: { password: "rentmate" }) { token } }`,
    },
  });
  const token = (await tokenRes.json()).data?.login?.token;

  return page.request.post(path, {
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    data: body,
  });
}

// ─── Test Suite ──────────────────────────────────────────────────────────────

test.describe('Task vendor flow (full stack)', () => {
  let vendorId: string;
  let vendorName: string;

  test.beforeAll(async ({ browser }) => {
    // Create a vendor via GraphQL before the test suite runs
    const page = await browser.newPage();
    const data = await gql(page, `
      mutation {
        createVendor(input: {
          name: "E2E Plumbing Co"
          contactMethod: "email"
          vendorType: "plumber"
        }) {
          uid
          name
        }
      }
    `);
    vendorId = data.createVendor.uid;
    vendorName = data.createVendor.name;
    await page.close();
  });

  test('create task from automation, see vendor conversation in chats, open it', async ({ page }) => {
    await login(page);

    // ── Step 1: Create a task with vendor assignment via the automation endpoint ──
    const createRes = await apiPost(page, '/automations/simulate/create-task', {
      subject: `E2E faucet repair ${Date.now()}`,
      body: 'Kitchen faucet is dripping badly, needs immediate attention.',
      category: 'plumbing',
      urgency: 'high',
      property_id: null,
      unit_id: null,
      assigned_vendor_id: vendorId,
      assigned_vendor_name: vendorName,
    });
    expect(createRes.ok()).toBe(true);
    const createBody = await createRes.json();
    expect(createBody).toEqual({ ok: true });

    // ── Step 2: Navigate to the Chats page ──
    await page.goto('/chats');
    await expect(page.getByRole('heading', { name: 'Chats' })).toBeVisible();

    // ── Step 3: Click the Vendors tab ──
    await page.getByRole('button', { name: 'Vendors' }).click();

    // ── Step 4: Wait for the vendor conversation to appear ──
    // The conversation title is the task subject
    const convCard = page.locator('text=E2E faucet repair').first();
    await expect(convCard).toBeVisible({ timeout: 10_000 });

    // ── Step 5: Click the conversation to open the chat panel ──
    await convCard.click();

    // ── Step 6: Verify the chat panel opens with the outreach message ──
    // The outreach message should be visible (generated by LLM, or if LLM is
    // unavailable, at minimum the conversation panel should open)
    const chatPanel = page.locator('[class*="chat"], [data-testid="chat-panel"]').first();
    await expect(chatPanel).toBeVisible({ timeout: 5_000 });
  });

  test('vendor conversation shows outreach message', async ({ page }) => {
    await login(page);

    // Create a task with a known subject
    const subject = `E2E outreach test ${Date.now()}`;
    await apiPost(page, '/automations/simulate/create-task', {
      subject,
      body: 'Leaky pipe under the kitchen sink.',
      category: 'plumbing',
      urgency: 'medium',
      property_id: null,
      unit_id: null,
      assigned_vendor_id: vendorId,
      assigned_vendor_name: vendorName,
    });

    // Navigate to Chats -> Vendors
    await page.goto('/chats');
    await page.getByRole('button', { name: 'Vendors' }).click();

    // Find and click the conversation
    const convCard = page.locator('text=E2E outreach test').first();
    await expect(convCard).toBeVisible({ timeout: 10_000 });
    await convCard.click();

    // The chat panel should open and show at least one message
    // (the AI-generated outreach or "RentMate" sender)
    await expect(page.getByText('RentMate').first()).toBeVisible({ timeout: 5_000 });
  });

  test('task without vendor has no vendor conversation in chats', async ({ page }) => {
    await login(page);

    const subject = `E2E no-vendor task ${Date.now()}`;
    await apiPost(page, '/automations/simulate/create-task', {
      subject,
      body: 'Gutters need seasonal cleaning.',
      category: 'maintenance',
      urgency: 'low',
      property_id: null,
      unit_id: null,
    });

    await page.goto('/chats');
    await page.getByRole('button', { name: 'Vendors' }).click();

    // Wait for the list to load, then confirm our task is NOT listed
    await page.waitForTimeout(2_000);
    await expect(page.locator(`text=${subject}`)).not.toBeVisible();
  });

  test('task appears in action desk after creation', async ({ page }) => {
    await login(page);

    const subject = `E2E action desk ${Date.now()}`;
    await apiPost(page, '/automations/simulate/create-task', {
      subject,
      body: 'Broken window latch.',
      category: 'maintenance',
      urgency: 'medium',
      property_id: null,
      unit_id: null,
      assigned_vendor_id: vendorId,
      assigned_vendor_name: vendorName,
    });

    await page.goto('/action-desk');

    // The task title should appear somewhere on the action desk
    await expect(page.locator(`text=${subject}`).first()).toBeVisible({ timeout: 10_000 });
  });

  test('resolve task from action desk', async ({ page }) => {
    await login(page);

    const subject = `E2E resolve ${Date.now()}`;
    const createRes = await apiPost(page, '/automations/simulate/create-task', {
      subject,
      body: 'Minor paint touch-up needed.',
      category: 'maintenance',
      urgency: 'low',
      property_id: null,
      unit_id: null,
      assigned_vendor_id: vendorId,
      assigned_vendor_name: vendorName,
    });
    expect(createRes.ok()).toBe(true);

    await page.goto('/action-desk');

    // Find and click the task
    const taskCard = page.locator(`text=${subject}`).first();
    await expect(taskCard).toBeVisible({ timeout: 10_000 });
    await taskCard.click();

    // The chat panel should open — look for a resolve/complete action
    // The task status should be changeable to "resolved"
    const resolveButton = page.getByRole('button', { name: /resolve|complete|close/i }).first();
    if (await resolveButton.isVisible({ timeout: 3_000 }).catch(() => false)) {
      await resolveButton.click();

      // After resolving, the task should show resolved status or disappear from active list
      await page.waitForTimeout(1_000);
    }
  });
});
